name: shared_task_list
description: A new Flutter application.
version: 1.6.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  uuid: ^3.0.4
  sqflite: ^2.0.0+3
  firebase_core: ^1.0.3
  firebase_database: ^7.0.0-dev.0
  path_provider: ^2.0.1
  path: ^1.8.0
  crypto: ^3.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.1
  flutter_localizations:
    sdk: flutter
  expandable: ^5.0.1
  flex_color_picker: ^2.0.0
  image_picker: ^0.7.4
  flutter_svg: ^0.21.0+1
  add_2_calendar: ^2.0.1
  flutter_speed_dial: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/image/add-to-calendar.svg
flutter_intl:
  enabled: true
