name: shared_task_list
description: A new Flutter application.
version: 1.4.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  flutter_custom_clippers: ^1.1.0
  uuid: ^2.0.4
  sqflite: ^1.2.0
  firebase_core: ^0.4.4
  firebase_database: ^3.1.1
  path_provider: ^1.5.1
  path: ^1.6.4
  crypto: ^2.1.3
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6
  flutter_speed_dial: ^1.2.5
  flutter_sliding_up_panel: ^0.0.3
  cupertino_icons: ^0.1.2
  pull_to_refresh: ^1.5.7
  intl: ^0.16.0
  global_configuration: ^1.4.0
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  expandable: ^4.1.2
  grouped_buttons: ^1.0.4
  flutter_material_color_picker: ^1.0.5
  image_picker: ^0.6.5
  flutter_svg: ^0.17.4
  add_2_calendar: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/image/add-to-calendar.svg
flutter_intl:
  enabled: true
