name: shared_task_list
description: A new Flutter application.
version: 1.4.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  flutter_custom_clippers: ^1.1.1
  uuid: ^2.0.4
  sqflite: ^1.3.0+1
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  path_provider: ^1.6.8
  path: ^1.6.4
  crypto: ^2.1.4
  rxdart: ^0.24.0
  shared_preferences: ^0.5.7+2
  flutter_sliding_up_panel: ^1.0.0
  cupertino_icons: ^0.1.3
  pull_to_refresh: ^1.5.8
  intl: ^0.16.1
  global_configuration: ^1.5.0
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  expandable: ^4.1.3
  grouped_buttons: ^1.0.4
  flutter_material_color_picker: ^1.0.5
  image_picker: ^0.6.6+1
  flutter_svg: ^0.17.4
  add_2_calendar: ^1.4.0
  flushbar: ^1.10.2
  flutter_speed_dial: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/image/add-to-calendar.svg
flutter_intl:
  enabled: true
