name: shared_task_list
description: Application for shared TODO list.
version: 1.7.2+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  uuid: ^3.0.4
  sqflite: ^2.0.0+3
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  path_provider: ^2.0.2
  path: ^1.8.0
  crypto: ^3.0.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.1
  flutter_localizations:
    sdk: flutter
  flex_color_picker: ^2.0.2
  image_picker: ^0.8.0+3
  flutter_svg: ^0.22.0
  add_2_calendar: ^2.1.0
  flutter_speed_dial: ^3.0.5
  another_flushbar: ^1.10.23
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/image/add-to-calendar.svg

flutter_intl:
  enabled: true
